### ISSUE TITLE
Validate Geodatabase Errors: Topology

### ISSUE THREAD

**Issue by aldunn4** [DOI-USGS/gems-tools-arcmap#91]
I am getting the following message when running the validate geodatabase tool. Can you give me more info on what this error means? 

Executing: ValidateDatabase2 D:\PuercoDam.gdb D:\PuercoDamValidation false false false
Start Time: Thu May  4 16:54:33 2023
Running script ValidateDatabase2...
GeMS_ValidateDatabase_Arc10.py, version of 14 November 2022
Looking at level 2 compliance
  scanning DataSources
  scanning DescriptionOfMapUnits
  scanning Glossary
  scanning GeoMaterialDict
  scanning ContactsAndFaults
  scanning MapUnitPolys
  checking GeologicMap to see if it has MUP and CAF feature classes
  checking topology of GeologicMap
    creating D:\PuercoDamValidation\PuercoDam_Validation.gdb/GeologicMap/GeologicMap_topology
    adding level 2 rules to topology:
      Must Not Overlap (Area)
Failed script ValidateDatabase2...

Traceback (most recent call last):
  File "O:\Style_and_Standards\DataModels\GeMS\gems-tools-arcmap-master\Scripts\GeMS_ValidateDatabase_Arc10.py", line 963, in <module>
    nTopoErrors = checkTopology(workdir,inGdb,outErrorsGdb,'GeologicMap',MUP,CAF,2)
  File "O:\Style_and_Standards\DataModels\GeMS\gems-tools-arcmap-master\Scripts\GeMS_ValidateDatabase_Arc10.py", line 298, in checkTopology
    arcpy.AddRuleToTopology_management(outTop, aRule, outMup)
  File "c:\program files (x86)\arcgis\desktop10.8\arcpy\arcpy\management.py", line 18907, in AddRuleToTopology
    raise e
ExecuteError: ERROR 999999: Error executing function.
A feature class has an invalid geometry type for the specified topology rule type.
Failed to execute (AddRuleToTopology).

Failed to execute (ValidateDatabase2).
Failed at Thu May  4 16:55:05 2023 (Elapsed Time: 32.35 seconds)

**Comment by aldunn4** [comment]
We don't have any feature classes that start with "ed_" or any prefixes that are different from any other geodatabase that the validate tool does work on.

**Comment by aldunn4** [comment]
I get the following message using the issue91 branch.

Executing: ValidateDatabase2
S:\temp\__STATEMAP_DELIVERABLES\2021-2022\_ToUSGS\PuercoDam\PuercoDam_Revisions\NM_2022_PuercoDam_4-1\NM_PuercoDam_4-1\NM_PuercoDam_4-1_database\PuercoDam.gdb
S:\temp\__STATEMAP_DELIVERABLES\2021-2022\_ToUSGS\PuercoDam\PuercoDam_Revisions\NM_2022_PuercoDam_4-1\NM_PuercoDam_4-1\Validation
false false false
Start Time: Fri May  5 10:53:51 2023
Running script ValidateDatabase2...
GeMS_ValidateDatabase_Arc10.py, version of 14 November 2022
Looking at level 2 compliance
  scanning DataSources
  scanning DescriptionOfMapUnits
  scanning Glossary
  scanning GeoMaterialDict
  scanning ContactsAndFaults
  scanning MapUnitPolys
  checking GeologicMap to see if it has MUP and CAF feature classes
Failed script ValidateDatabase2...

Traceback (most recent call last):
  File
"S:\temp\__STATEMAP_DELIVERABLES\2021-2022\_ToUSGS\PuercoDam\PuercoDam_Revisions\NM_2022_PuercoDam_4-1\NM_PuercoDam_4-1\NM_PuercoDam_4-1_database\gems-tools-arcmap-issue91\Scripts\GeMS_ValidateDatabase_Arc10.py",
line 962, in <module>
    isMap,MUP,CAF = isFeatureDatasetAMap('GeologicMap')
  File
"S:\temp\__STATEMAP_DELIVERABLES\2021-2022\_ToUSGS\PuercoDam\PuercoDam_Revisions\NM_2022_PuercoDam_4-1\NM_PuercoDam_4-1\NM_PuercoDam_4-1_database\gems-tools-arcmap-issue91\Scripts\GeMS_ValidateDatabase_Arc10.py",
line 260, in isFeatureDatasetAMap
    desc = arcpy.da.Describe(fc)
AttributeError: 'module' object has no attribute 'Describe'

Failed to execute (ValidateDatabase2).
Failed at Fri May  5 10:56:55 2023 (Elapsed Time: 3 minutes 3 seconds)

*Amy Dunn*
She/her
GIS Technician/Cartographer
Map Rockstar
New Mexico Bureau of Geology and Mineral Resources

Office #: 362C
Office: 575-835-5501
Cell: 906-370-9248
***@***.***
NMBGMR Staff Page <https://geoinfo.nmt.edu/staff/detail.cfml?name=dunn>

New Mexico Institute of Mining and Technology
801 Leroy Pl
Socorro, NM 87801

106.9048°W, 34.06804°N NAD 83
Elevation: 4623 ft | 1409 m

**Comment by ethoms-usgs** [comment]
Ah, sorry. Wrong method. That has been fixed and David Ahumada sent me a screenshot of the contents of the gdb. I believe the tool was confused by the points feature class called MapUnitPolysLabels. I put that into my test gdb and the tool ran correctly, so I think that was the issue.

**Comment by aldunn4** [comment]
Thanks, it works!

*Amy Dunn*
She/her
GIS Technician/Cartographer
Map Rockstar
New Mexico Bureau of Geology and Mineral Resources

Office #: 362C
Office: 575-835-5501
Cell: 906-370-9248
***@***.***
NMBGMR Staff Page <https://geoinfo.nmt.edu/staff/detail.cfml?name=dunn>

New Mexico Institute of Mining and Technology
801 Leroy Pl
Socorro, NM 87801

106.9048°W, 34.06804°N NAD 83
Elevation: 4623 ft | 1409 m

**Comment by ethoms-usgs** [comment]
Great! I will close the issue.
